SoundTube/config/routes.rb
Rails.application.routes.draw do
  resources :video
  resources :explore

  root 'welcome#homepage'

  resources :channel, only: [:index, :get_playlist_videos, :get_video_link, :playlists_count, :new, :playlists ]

end

SoundTube/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

SoundTube/app/controllers/explore_controller.rb
API_KEY = 'AIzaSyAOziHAdhr38lpl75KX8Qkbh7eGtxyWfPw'
Yt.configure do |config|
  config.api_key = API_KEY
  config.log_level = :debug
end

class ExploreController < ApplicationController
  def index
    @playlist = Yt::Playlist.new id: 'PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI'
    @items_collection = []
		@playlist.playlist_items.each do |item|
				@items_collection.push item.video_id
		end

		@items = Kaminari.paginate_array(@items_collection).page(params[:page]).per(20)
		respond_to do |format|
			format.js
			format.html
		end
  end
end

SoundTube/app/controllers/video_controller.rb
API_KEY = 'AIzaSyAOziHAdhr38lpl75KX8Qkbh7eGtxyWfPw'
Yt.configure do |config|
  config.api_key = API_KEY
end

class VideoController < ApplicationController

  def show
    @channel = Yt::Channel.new id: params[:id]
		@playlists = @channel.playlists
		@items_collection = []
    c = 0
		@playlists.each do |playlist|
      break if c > 1
      c += 1
			get_playlist_videos(playlist.id).each do |item|
				@items_collection.push item.video_id
        print item.video_id
			end
		end
		@items = Kaminari.paginate_array(@items_collection).page(params[:page]).per(20)
		puts @items
		respond_to do |format|
			format.js
			format.html
		end
  end

	def get_playlist_videos (playlist_id)
    playlist = Yt::Playlist.new id: playlist_id
    playlist.playlist_items
	end

end

SoundTube/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end
end

SoundTube/app/helpers/application_helper.rb
module ApplicationHelper
end

SoundTube/app/helpers/explore_helper.rb
module ExploreHelper
end

SoundTube/app/helpers/video_helper.rb
module VideoHelper
end

SoundTube/app/helpers/welcome_helper.rb
module WelcomeHelper
end

SoundTube/app/views/explore/_items.html.erb
<% @items.each do |video_id| %>
    <div class="col-md-3">
        <div class="embed-responsive embed-responsive-4by3">
            <iframe class="embed-responsive-item" src= "//www.youtube.com/embed/<%= video_id %>"></iframe>
        </div>
        <br>
    </div>
<% end %>     

SoundTube/app/views/explore/index.html.erb
<!DOCTYPE html>
<html lang="en">
<link href="css/bootstrap.css" rel="stylesheet">
<body>

    <!-- style Grid Section -->
    <div class="ajax-progress"></div>
    <section class="bg-light-gray">
    <div class="container">
      <div class="content">
        <div id="items">
            <%= render 'items' %>
        </div>
        <div class="pagination">
          <div id="paginator">
              <%= paginate @items, :remote => true %>
          </div>
        </div>
      </div>
    </div>

    </section>
    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="js/classie.js"></script>
    <script src="js/cbpAnimatedHeader.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/agency.js"></script>

</body>

</html>

SoundTube/app/views/explore/show.html.erb
<!DOCTYPE html>
<html lang="en">
<link href="css/bootstrap.css" rel="stylesheet">
<body>

  <header class="style-header">
      <div class="container">
          <div class="intro-text">
              <div class="intro-heading" align="left">Explore popular this week</div>
          </div>
      </div>
  </header>
    <!-- style Grid Section -->
    <div class="ajax-progress"></div>
    <section class="bg-light-gray">
    <div class="container">
      <div class="content">
        <div id="items">
            <%= render 'items' %>
        </div>
        <div class="pagination">
          <div id="paginator">
              <%= paginate @items, :remote => true %>
          </div>
        </div>
      </div>
    </div>

    </section>
    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="js/classie.js"></script>
    <script src="js/cbpAnimatedHeader.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/agency.js"></script>

</body>

</html>

SoundTube/app/views/explore/show.js.erb
$('#items').html("<%= escape_javascript(render 'items') %>");
$('#paginator').html("<%= escape_javascript(paginate(@items, :remote => true).to_s) %>");

SoundTube/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoundTube</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/agency.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "SoundTube", root_path, class: "navbar-brand page-scroll" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <%= link_to "Explore", explore_index_path, :class=>"style-link" %>
                    </li>
                    <li>
                        <%= link_to "Styles", root_path, :class=>"style-link"  %>
                    </li>
                  <!--  <li>
                        <a class="page-scroll" href="#search">Search<i class="fa fa-search-plus"></i></a>
                    </li>-->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

<%= yield %>

</body>
</html>

SoundTube/app/views/video/_items.html.erb
<% @items.each do |video_id| %>
    <div class="col-md-3">
        <div class="embed-responsive embed-responsive-4by3">
            <iframe class="embed-responsive-item" src= "//www.youtube.com/embed/<%= video_id %>"></iframe>
        </div>
        <br>
    </div>
<% end %>     

SoundTube/app/views/video/show.html.erb
<!DOCTYPE html>
<html lang="en">
<link href="css/bootstrap.css" rel="stylesheet">
<body>

    <!-- style Grid Section -->
    <div class="ajax-progress"></div>
    <section class="bg-light-gray">
    <div class="container">
      <div class="content">
        <div id="items">
            <%= render 'items' %>
        </div>
        <div class="pagination">
          <div id="paginator">
              <%= paginate @items, :remote => true %>
          </div>
        </div>
      </div>
    </div>

    </section>
    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="js/classie.js"></script>
    <script src="js/cbpAnimatedHeader.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/agency.js"></script>

</body>

</html>

SoundTube/app/views/video/show.js.erb
$('#items').html("<%= escape_javascript(render 'items') %>");
$('#paginator').html("<%= escape_javascript(paginate(@items, :remote => true).to_s) %>");

SoundTube/app/views/welcome/homepage.html.erb
<!DOCTYPE html>
<html lang="en">
<body id="page-top" class="index">
    <!-- Header -->
    <header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in">Welcome To SoundTube!</div>
                <div class="intro-heading">Listen to music, no limits. Anywhere, anytime.</div>
            </div>
        </div>
    </header>

    <!-- style Grid Section -->
    <section id="style" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">styles</h2>
                    <h3 class="section-subheading text-muted">Choose a style you like the most.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 style-item">
                    <%= link_to video_path('UCE80FOXpJydkkMo-BYoJdEg'), :class=>"style-link" do %>
                        <div class="carousel-caption">
                            <h3 class="section-heading">#Pop</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Pop</h3>
                            </div>
                        </div>
                        <img src="assets/style/pop.jpg" class="img-responsive" alt="">
                    <% end %>
                </div>
                <div class="col-md-3 style-item">
                    <%= link_to video_path('UCCIPrrom6DIftcrInjeMvsQ'), :class=>"style-link" do %>
                        <div class="carousel-caption">
                            <h3 class="section-heading">#Electro</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Electro</h3>
                            </div>
                        </div>
                        <img src="assets/style/electro2.jpg" class="img-responsive" alt="">
                    <% end %>
                </div>
                <div class="col-md-3 style-item">
                    <%= link_to video_path('UCUnSTiCHiHgZA9NQUG6lZkQ'), :class=>"style-link" do %>
                        <div class="carousel-caption">
                            <h3 class="section-heading">#Hip-hop</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Hip-hop</h3>
                            </div>
                        </div>
                        <img src="assets/style/hip-hop.jpg" class="img-responsive" alt="">
                    <% end %>
                </div>
                <div class="col-md-3 style-item">
                    <%= link_to video_path('UCRZoK7sezr5KRjk7BBjmH6w'), :class=>"style-link" do %>
                        <div class="carousel-caption">
                            <h3 class="section-heading">#Rock</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Rock</h3>
                            </div>
                        </div>
                        <img src="assets/style/rock.jpg" class="img-responsive" alt="">
                   <% end %>
                </div>
                <div class="col-md-3 style-item">
                    <%= link_to video_path('UCvwDeZSN2oUHlLWYRLvKceA'), :class=>"style-link" do %>
                        <div class="carousel-caption">
                            <h3 class="section-heading">#Blues</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Blues</h3>
                            </div>
                        </div>
                        <img src="assets/style/blues.jpg" class="img-responsive" alt="">
                    <% end %>
                </div>
                <div class="col-md-3 style-item">
                    <%= link_to video_path('UCsFaF_3y_L__y8kWAIEhv1w'), :class=>"style-link" do %>
                        <div class="carousel-caption">
                            <h3 class="section-heading">#Soul</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Soul</h3>
                            </div>
                        </div>
                        <img src="assets/style/soul.jpg" class="img-responsive" alt="">
                    <% end %>
                </div>
                  <div class="col-md-3 style-item">
                    <%= link_to video_path('UCEdvzYtzTH_FFpB3VRjFV6Q'), :class=>"style-link" do %>
                        <div class="carousel-caption">
                            <h3 class="section-heading">#Reggae</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Reggae</h3>
                            </div>
                        </div>
                        <img src="assets/style/reggae.jpg" class="img-responsive" alt="">
                    <% end %>
                </div>
                  <div class="col-md-3 style-item">
                    <%= link_to video_path('UClYMFaf6IdjQnZmsnw9N1hQ'), :class=>"style-link" do %>
                        <div class="carousel-caption">
                            <h3 class="section-heading">#Country</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Country</h3>
                            </div>
                        </div>
                        <img src="assets/style/country.jpg" class="img-responsive" alt="">
                    <% end %>
                </div>
                  <div class="col-md-3 style-item">
                    <%= link_to video_path('UCxk1wRJGOTmzJAbvbQ8VicQ'), :class=>"style-link" do %>
                        <div class="carousel-caption">
                            <h3 class="section-heading">#Funk</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Funk</h3>
                            </div>
                        </div>
                        <img src="assets/style/funk.jpg" class="img-responsive" alt="">
                    <% end %>
                </div>
                  <div class="col-md-3 style-item">
                    <%= link_to video_path('UC7KZmdQxhcajZSEFLJr3gCg'), :class=>"style-link" do %>
                        <div class="carousel-caption">
                            <h3 class="section-heading">#Jazz</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Jazz</h3>
                            </div>
                        </div>
                        <img src="assets/style/jazz.jpg" class="img-responsive" alt="">
                    <% end %>
                </div>
                  <div class="col-md-3 style-item">
                    <%= link_to video_path('UCNGkvx5UwHzqlo6zDgRDYsQ'), :class=>"style-link" do %>
                       <div class="carousel-caption">
                            <h3 class="section-heading">#Disco</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Disco</h3>
                            </div>
                        </div>
                        <img src="assets/style/disco.jpg" class="img-responsive" alt="">
                    <% end %>
                </div>
                  <div class="col-md-3 style-item">
                    <%= link_to video_path('UCLwMU2tKAlCoMSbGQDuiMSg'), :class=>"style-link" do %>
                        <div class="carousel-caption">
                            <h3 class="section-heading">#Classical</h3>
                        </div>
                        <div class="style-hover">
                            <div class="carousel-caption">
                                <h3 class="section-heading">#Classical</h3>
                            </div>
                        </div>
                        <img src="assets/style/classical.jpg" class="img-responsive" alt="">
                    <% end %>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="js/classie.js"></script>
    <script src="js/cbpAnimatedHeader.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/agency.js"></script>

</body>

</html>